import { Expert } from '@/types';

export const MOCK_EXPERTS: Expert[] = [
  {
    id: 'exp_1',
    name: 'CA Priya Sharma',
    type: 'ca',
    qualification: 'CA Final, DISA',
    experience: 8,
    states: ['Gujarat', 'Maharashtra', 'Rajasthan'],
    industries: ['manufacturing', 'trading', 'retail'],
    languages: ['Hindi', 'English', 'Gujarati'],
    hourlyRate: 1500,
    consultationFee: 500,
    rating: 4.8,
    totalConsultations: 234,
    bio: 'Specializes in GST compliance, MSME schemes, and manufacturing sector taxation.',
    available: true,
    avatar: 'PS'
  },
  {
    id: 'exp_2',
    name: 'Adv. Rakesh Bora',
    type: 'lawyer',
    qualification: 'LLB, Corporate Law Specialist',
    experience: 12,
    states: ['Assam', 'West Bengal', 'Meghalaya'],
    industries: ['all'],
    languages: ['Hindi', 'English', 'Assamese', 'Bengali'],
    hourlyRate: 2000,
    consultationFee: 800,
    rating: 4.9,
    totalConsultations: 189,
    bio: 'Northeast India expansion expert. Assam industrial policy, FSSAI, and labor law specialist.',
    available: true,
    avatar: 'RB'
  },
  {
    id: 'exp_3',
    name: 'Amit Verma (CA Student)',
    type: 'student',
    qualification: 'CA Final Articleship, BCom',
    experience: 2,
    states: ['Delhi', 'Uttar Pradesh', 'Haryana'],
    industries: ['service', 'retail', 'trading'],
    languages: ['Hindi', 'English'],
    hourlyRate: 300,
    consultationFee: 150,
    rating: 4.6,
    totalConsultations: 67,
    bio: 'Affordable GST filing assistance, scheme discovery, document organization.',
    available: true,
    avatar: 'AV'
  },
  {
    id: 'exp_4',
    name: 'CA Deepa Nair',
    type: 'ca',
    qualification: 'CA, MBA Finance',
    experience: 6,
    states: ['Kerala', 'Karnataka', 'Tamil Nadu'],
    industries: ['service', 'technology', 'healthcare'],
    languages: ['Hindi', 'English', 'Malayalam', 'Tamil'],
    hourlyRate: 1800,
    consultationFee: 600,
    rating: 4.7,
    totalConsultations: 156,
    bio: 'South India specialist. Startup India, DPIIT recognition, angel tax exemptions.',
    available: true,
    avatar: 'DN'
  },
  {
    id: 'exp_5',
    name: 'Sunita Patel (CA Student)',
    type: 'student',
    qualification: 'CA Inter, BCom Hons',
    experience: 1,
    states: ['Gujarat', 'Rajasthan'],
    industries: ['manufacturing', 'trading'],
    languages: ['Hindi', 'English', 'Gujarati'],
    hourlyRate: 250,
    consultationFee: 100,
    rating: 4.4,
    totalConsultations: 34,
    bio: 'Assists with Udyam registration, scheme applications, GST return prep.',
    available: true,
    avatar: 'SP'
  }
];
